In [36]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import risk_kit as rk

hfi = rk.get_hfi_returns()
er = rk.annualize_rets(hfi["2000":], 12)
cov = hfi["2000":].cov()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


/Users/ahmet/Desktop/Investment Banking & Asset Management/Investment-Banking-Asset-Management/risk_kit.py:41: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  hfi = pd.read_csv("data/edhec-hedgefundindices.csv",


In [49]:
col_of_interest = ["Distressed Securities"]
rk.var_gaussian(hfi["2000":][col_of_interest], level = 1)


Distressed Securities    0.03143
dtype: float64

In [50]:
rk.var_gaussian(hfi["2000":][col_of_interest], level = 1, modified=True)

Distressed Securities    0.049669
dtype: float64

In [51]:
rk.var_historic(hfi["2000":][col_of_interest], level=1)

Distressed Securities    0.042642
dtype: float64

In [39]:
ind = rk.get_ind_returns()
er = rk.annualize_rets(ind["2013":"2017"], 12)
cov = ind["2013":"2017"].cov()

In [40]:
l = ["Books", "Steel", "Oil", "Mines"]
msr = rk.msr(0.1, er[l], cov.loc[l,l])
msr

array([1.76247905e-15, 1.00000000e+00, 2.39391840e-16, 0.00000000e+00])

In [26]:
n = er[l].shape[0]
w_ew = np.repeat(1/n, n)
w_ew

array([0.25, 0.25, 0.25, 0.25])

In [41]:
gmv = rk.gmv(cov.loc[l, l])
gmv

array([0.47702487, 0.        , 0.43411203, 0.0888631 ])

In [58]:
cov = ind["2018"].cov()
msr_vol = rk.portfolio_vol(msr, cov.loc[l, l]) * np.sqrt(12)
(msr_vol*100).round(2)

/var/folders/hh/1qw11svj2913226t4vlc07b00000gn/T/ipykernel_59065/2343745923.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  cov = ind["2018"].cov()


21.98

In [34]:
gmv_vol = rk.portfolio_vol(gmv, ind["2018"][l].cov())
rk.annualize_vol(gmv_vol, 12)

/var/folders/hh/1qw11svj2913226t4vlc07b00000gn/T/ipykernel_59065/3300297697.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  gmv_vol = rk.portfolio_vol(gmv, ind["2018"][l].cov())


0.0